name: Deploy Parser (Google Apps Script)

on:
  push:
    branches:
      - main
    paths:
      - 'parser/**'
  workflow_dispatch:

jobs:
  deploy-parser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Create clasp config
        run: |
          echo '{"scriptId":"${{ secrets.GAS_SCRIPT_ID }}","rootDir":"parser"}' > .clasp.json

      - name: Authenticate clasp
        env:
          CLASPRC_CONTENT: ${{ secrets.GAS_CLASPRC_JSON }}
        run: |
          printf '%s' "$CLASPRC_CONTENT" > ~/.clasprc.json
          chmod 644 ~/.clasprc.json

      - name: Push code to Apps Script
        run: |
          echo $CLASPRC_JSON
          cat ~/.clasprc.json
          npx @google/clasp push --force
        working-directory: parser
        env:
          CLASPRC_JSON: ${{ secrets.GAS_CLASPRC_JSON }}

      - name: Create new deployment
        run: clasp deploy --description "Deploy ${{ github.sha }}"
        working-directory: parser
        env:
          CLASPRC_JSON: ${{ secrets.GAS_CLASPRC_JSON }}
